# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i-do0t_MqQ8UkErI5dGjeXQqTiSf0RhV
"""

#Importing libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

# Load mass_balance dataset
df = pd.read_csv("/content/drive/MyDrive/Copy of mass_balance_point.csv")

# Filter years from 2005 to 2025
df = df[(df["year"] >= 2005) & (df["year"] <= 2025)]

# Keep useful countries / regions
df = df[df["country"].isin(["IN", "NP", "BT", "CN"])]

# Remove missing target values
df = df.dropna(subset=["balance"])

# Create sub-region
def region(country):
    if country == "IN":
        return "Western Himalaya"
    elif country == "NP":
        return "Central Himalaya"
    elif country == "BT":
        return "Eastern Himalaya"
    elif country == "CN":
        return "Tibetan HMA"
    else:
        return "Other"

df["sub_region"] = df["country"].apply(region)

# Select features and target
features = ["year", "latitude", "longitude", "elevation", "sub_region"]
target = "balance"

# Remove rows with missing feature values
df_model = df.dropna(subset=features + [target])

X = df_model[features]
y = df_model[target]

# Split data into training and testing set
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Numeric and categorical columns
numeric_features = ["year", "latitude", "longitude", "elevation"]
categorical_features = ["sub_region"]

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ],
    remainder="passthrough"
)

# Using Linear Regression and Random Forest Regression Model
models = {
    "Linear Regression": LinearRegression(),
    "Random Forest Regression": RandomForestRegressor(
        n_estimators=200,
        random_state=42
    )
}

# Train and evaluate the mean absolute error, root mean square error, and r-square
results = []

for name, model in models.items():
    pipeline = Pipeline(
        steps=[
            ("preprocessor", preprocessor),
            ("model", model)
        ]
    )

    pipeline.fit(X_train, y_train)
    predictions = pipeline.predict(X_test)

    mae = mean_absolute_error(y_test, predictions)
    rmse = np.sqrt(mean_squared_error(y_test, predictions))
    r2 = r2_score(y_test, predictions)

    results.append([name, mae, rmse, r2])

results_df = pd.DataFrame(
    results,
    columns=["Model", "MAE", "RMSE", "R2"]
)

print(results_df)



from google.colab import drive
drive.mount('/content/drive')